### ISSUE TITLE
Not glimmer-related, but a tiny display-related issue at http://andymaleh.blogspot.com/

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer#14]
Hey Andy,

Sorry for misusing the github issue tracker for glimmer, but I thought it is better to
report an issue than send an email. :D

I read the blog every now and then to keep up to date with things that changed. \o/

There is, however had, a small visual annoyance at http://andymaleh.blogspot.com/
in my opinion: the background image makes it hard to read the text as-is. Not
necessarily everywhere, but in particular when the background is white or grey.

This is a bit hard to explain, so I uploaded an example to imgur:

https://i.imgur.com/xXpRtsc.png

I deliberately chopped this off, so if you look at the bottom right corner of that
image, I think you can quickly see the problem: that ~white rectangle 
kind of flows into the white font colour and the orange font colour. It's a
very minor thing, not sure if it is worth reporting, but I just report it in
the event it may have been missed.

There are various ways to improve this (if you come to the same conclusion
that this is not ideal). I'll give just two suggestions but of course there are
 others. A simple one is to have the whole main div for the blog content
have a black background. That should solve this easily.

The drawback is that the background image can not be seen. So the
second suggestion may be to fiddle around with opaque in CSS.
Not sure if it is via e. g. opacity: 0.5; but something to e. g. have the
background blackish, but a bit transparent still, with the idea that the
background still gets a stronger contrast (e. g. the changed div
would be a bit darker than before, but not totally black-ish). Anyway
that's it, keep the glimmer spirit up! \o/

**Comment by AndyObtiva** [comment]
Thank you for reporting!

I just updated the blog's layout to have a less transparent background behind the main article text, bigger text, and bigger code text.

How does it look now? Your feedback is appreciated.

![Screen Shot 2021-12-11 at 2 30 14 PM](https://user-images.githubusercontent.com/23052/145689185-c174762c-b3e1-4c08-9bc8-5856f9034b31.png)

**Comment by rubycoder** [comment]
I was OK with the blog the way it was, but this is a definite improvement
in readability!!!

Thanks to Andy and to rubyFeedback

Wayne
