### ISSUE TITLE
[Proposal] A new glimmer FAQ repository to specifically answer FAQ-related questions from different users

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer#45]
**Universal Glimmer FAQ**

Hey there Andy - long time no opening new issue trackers by me. :D

You provide at the least one FAQ, which is here:

https://github.com/AndyObtiva/glimmer?tab=readme-ov-file#faq

I am not sure if there are more FAQ-entries in regards to glimmer
than this one though.

The FAQ shown above currently answers 6 questions.

I would like to suggest a "Universal Glimmer FAQ", spanning ALL
glimmer-related aspects, but also questions as to how real people
may use Glimmer.

With that I, sort of, mean one central place where the Glimmer
FAQ could be situated at.

I also, specifically, mean really small-ish questions too, such
as "how to style xyz" - such as the glimmer-editor (glimmer-cs-gladiator).

Now you may interject and state that this fits more to the corresponding
github page for the glimmer subsuite at hand, such as glimmer-gtk, 
glimmer-tk and so forth. I understand this, but I also think that having
one unified place for a glimmer FAQ - which I see more as a "practical
documentation" would be better. It may make it easier for people
to find something interesting or even learn something new.

In order to accomodate this, I would like to suggest adding a new
github repository, specifically as a glimmer FAQ, inviting people to
ask glimmer-related questions.

You could try this, and if it works then this is great - if it does
not work, you could always merge it back into the glimmer main 
repository and delete that new github account, so this should be 
low risk approach.

I also have some glimmer-related questions, but I feel that it may be
better to add them to such a new github page, rather than spam down
the main github repository with FAQ-related questions.

As always please feel free to proceed as you may deem fit, including
disregarding this issue request and closing it as you deem fit.

**Comment by AndyObtiva** [comment]
I don't believe that's a good idea as most people expect info to live in the github repos of the projects they concern.

That said, if you find this useful, you are welcome to create it, or create a GitHub repo that is a general tutorial for Glimmer, not just FAQ. I'm not stopping you. You can do whatever you want in your own repo.

If you have questions, please ask on the [Glimmer Gitter chat](https://gitter.im/AndyObtiva/glimmer?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). Or, if you prefer, you can ask me here.

I am closing this for now though given my answer above.
