### ISSUE TITLE
Problem with initial scaffolding - no auto Rakefile creation then "no implicit conversion from nil to integer"

### ISSUE THREAD

**Issue by mistergibson** [AndyObtiva/glimmer#6]
mkdir some_app
glimmer scaffold[some_app]
Successfully installed juwelier-2.4.9
1 gem installed
No user.name found in ~/.gitconfig. Please tell git about yourself (see http://help.github.com/git-email-settings/ for details). For example: git config --global user.name "mad voo"
Created some_app/.gitignore
Created some_app/.ruby-version
Created some_app/.ruby-gemset
Created some_app/VERSION
Created some_app/LICENSE.txt
Created some_app/Gemfile
warning: thread "Ruby-0-Thread-1: /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/launcher.rb:187" terminated with exception (report_on_exception is true):
#<Class:0x5c7e92df>: No such file or directory - Rakefile
                 sysopen at org/jruby/RubyIO.java:1237
                    read at org/jruby/RubyIO.java:3774
            gem_rakefile at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task/scaffold.rb:419
                     app at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task/scaffold.rb:136
                  <main> at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task.rb:113
                 execute at /opt/jruby/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:273
                    each at org/jruby/RubyArray.java:1809
                 execute at /opt/jruby/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:273
  invoke_with_call_chain at /opt/jruby/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:214
         mon_synchronize at /opt/jruby/lib/ruby/stdlib/monitor.rb:235
  invoke_with_call_chain at /opt/jruby/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:194
                  invoke at /opt/jruby/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:183
                  launch at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/launcher.rb:140
      launch_application at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/launcher.rb:188
#<Class:0x5c7e92df>: No such file or directory - Rakefile
                 sysopen at org/jruby/RubyIO.java:1237
                    read at org/jruby/RubyIO.java:3774
            gem_rakefile at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task/scaffold.rb:419
                     app at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task/scaffold.rb:136
                  <main> at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task.rb:113
                 execute at /opt/jruby/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:273
                    each at org/jruby/RubyArray.java:1809
                 execute at /opt/jruby/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:273
  invoke_with_call_chain at /opt/jruby/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:214
         mon_synchronize at /opt/jruby/lib/ruby/stdlib/monitor.rb:235
  invoke_with_call_chain at /opt/jruby/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:194
                  invoke at /opt/jruby/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:183
                  launch at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/launcher.rb:140
      launch_application at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/launcher.rb:188

So ... I help it along by creating the some_app/Rakefile and retry:

nano some_app/Rakefile
glimmer scaffold[some_app]
Successfully installed juwelier-2.4.9
1 gem installed
No user.name found in ~/.gitconfig. Please tell git about yourself (see http://help.github.com/git-email-settings/ for details). For example: git config --global user.name "mad voo"
Created some_app/.gitignore
Created some_app/.ruby-version
Created some_app/.ruby-gemset
Created some_app/VERSION
Created some_app/LICENSE.txt
Created some_app/Gemfile
warning: thread "Ruby-0-Thread-1: /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/launcher.rb:187" terminated with exception (report_on_exception is true):
#<Class:0x7cdecc64>: no implicit conversion from nil to integer
                  insert at org/jruby/RubyArray.java:1101
            gem_rakefile at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task/scaffold.rb:422
                     app at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task/scaffold.rb:136
                  <main> at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task.rb:113
                 execute at /opt/jruby/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:273
                    each at org/jruby/RubyArray.java:1809
                 execute at /opt/jruby/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:273
  invoke_with_call_chain at /opt/jruby/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:214
         mon_synchronize at /opt/jruby/lib/ruby/stdlib/monitor.rb:235
  invoke_with_call_chain at /opt/jruby/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:194
                  invoke at /opt/jruby/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:183
                  launch at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/launcher.rb:140
      launch_application at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/launcher.rb:188
#<Class:0x7cdecc64>: no implicit conversion from nil to integer
                  insert at org/jruby/RubyArray.java:1101
            gem_rakefile at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task/scaffold.rb:422
                     app at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task/scaffold.rb:136
                  <main> at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task.rb:113
                 execute at /opt/jruby/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:273
                    each at org/jruby/RubyArray.java:1809
                 execute at /opt/jruby/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:273
  invoke_with_call_chain at /opt/jruby/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:214
         mon_synchronize at /opt/jruby/lib/ruby/stdlib/monitor.rb:235
  invoke_with_call_chain at /opt/jruby/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:194
                  invoke at /opt/jruby/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:183
                  launch at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/launcher.rb:140
      launch_application at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/launcher.rb:188

This happens no matter what I try --> it just gets stopped here.

**Comment by AndyObtiva** [comment]
You got an error on top that you may have not addressed yet:
No user.name found in ~/.gitconfig. Please tell git about yourself (see http://help.github.com/git-email-settings/ for details). For example: git config --global user.name "mad voo"

**Comment by mistergibson** [comment]
Ok, got that stuff taken care of but I still get this error:

warning: thread "Ruby-0-Thread-1: /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/launcher.rb:187" terminated with exception (report_on_exception is true):
#<Class:0x5e472aff>: no implicit conversion from nil to integer
                  insert at org/jruby/RubyArray.java:1101
            gem_rakefile at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task/scaffold.rb:422
                     app at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task/scaffold.rb:136
                  <main> at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task.rb:113
                 execute at /opt/jruby/lib/ruby/gems/shared/gems/rake-13.0.1/lib/rake/task.rb:279
                    each at org/jruby/RubyArray.java:1809
                 execute at /opt/jruby/lib/ruby/gems/shared/gems/rake-13.0.1/lib/rake/task.rb:279
  invoke_with_call_chain at /opt/jruby/lib/ruby/gems/shared/gems/rake-13.0.1/lib/rake/task.rb:219
         mon_synchronize at /opt/jruby/lib/ruby/stdlib/monitor.rb:235
  invoke_with_call_chain at /opt/jruby/lib/ruby/gems/shared/gems/rake-13.0.1/lib/rake/task.rb:199
                  invoke at /opt/jruby/lib/ruby/gems/shared/gems/rake-13.0.1/lib/rake/task.rb:188
                  launch at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/launcher.rb:140
      launch_application at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/launcher.rb:188
#<Class:0x5e472aff>: no implicit conversion from nil to integer
                  insert at org/jruby/RubyArray.java:1101
            gem_rakefile at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task/scaffold.rb:422
                     app at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task/scaffold.rb:136
                  <main> at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task.rb:113
                 execute at /opt/jruby/lib/ruby/gems/shared/gems/rake-13.0.1/lib/rake/task.rb:279
                    each at org/jruby/RubyArray.java:1809
                 execute at /opt/jruby/lib/ruby/gems/shared/gems/rake-13.0.1/lib/rake/task.rb:279
  invoke_with_call_chain at /opt/jruby/lib/ruby/gems/shared/gems/rake-13.0.1/lib/rake/task.rb:219
         mon_synchronize at /opt/jruby/lib/ruby/stdlib/monitor.rb:235
  invoke_with_call_chain at /opt/jruby/lib/ruby/gems/shared/gems/rake-13.0.1/lib/rake/task.rb:199
                  invoke at /opt/jruby/lib/ruby/gems/shared/gems/rake-13.0.1/lib/rake/task.rb:188
                  launch at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/launcher.rb:140
      launch_application at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/launcher.rb:188

**Comment by AndyObtiva** [comment]
Did you delete the previously half generated app before scaffolding again? If not, make sure to do so. Let me know what OS you are on if you run into trouble again.

**Comment by mistergibson** [comment]
I blew out all the old cruft and tried again:

 sudo glimmer scaffold[gxg_studio_glimmer]
[sudo] password for mistergibson:              
Successfully installed juwelier-2.4.9
1 gem installed
Please specify --github-username or set github.user in ~/.gitconfig (see http://github.com/blog/180-local-github-config for details). For example: git config --global github.user defunkt
Created gxg_studio_glimmer/.gitignore
Created gxg_studio_glimmer/.ruby-version
Created gxg_studio_glimmer/.ruby-gemset
Created gxg_studio_glimmer/VERSION
Created gxg_studio_glimmer/LICENSE.txt
Created gxg_studio_glimmer/Gemfile
warning: thread "Ruby-0-Thread-1: /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/launcher.rb:187" terminated with exception (report_on_exception is true):
#<Class:0x357a68f9>: no implicit conversion from nil to integer
                  insert at org/jruby/RubyArray.java:1101
            gem_rakefile at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task/scaffold.rb:422
                     app at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task/scaffold.rb:136
                  <main> at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task.rb:113
                 execute at /opt/jruby/lib/ruby/gems/shared/gems/rake-13.0.1/lib/rake/task.rb:279
                    each at org/jruby/RubyArray.java:1809
                 execute at /opt/jruby/lib/ruby/gems/shared/gems/rake-13.0.1/lib/rake/task.rb:279
  invoke_with_call_chain at /opt/jruby/lib/ruby/gems/shared/gems/rake-13.0.1/lib/rake/task.rb:219
         mon_synchronize at /opt/jruby/lib/ruby/stdlib/monitor.rb:235
  invoke_with_call_chain at /opt/jruby/lib/ruby/gems/shared/gems/rake-13.0.1/lib/rake/task.rb:199
                  invoke at /opt/jruby/lib/ruby/gems/shared/gems/rake-13.0.1/lib/rake/task.rb:188
                  launch at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/launcher.rb:140
      launch_application at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/launcher.rb:188
#<Class:0x357a68f9>: no implicit conversion from nil to integer
                  insert at org/jruby/RubyArray.java:1101
            gem_rakefile at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task/scaffold.rb:422
                     app at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task/scaffold.rb:136
                  <main> at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/rake_task.rb:113
                 execute at /opt/jruby/lib/ruby/gems/shared/gems/rake-13.0.1/lib/rake/task.rb:279
                    each at org/jruby/RubyArray.java:1809
                 execute at /opt/jruby/lib/ruby/gems/shared/gems/rake-13.0.1/lib/rake/task.rb:279
  invoke_with_call_chain at /opt/jruby/lib/ruby/gems/shared/gems/rake-13.0.1/lib/rake/task.rb:219
         mon_synchronize at /opt/jruby/lib/ruby/stdlib/monitor.rb:235
  invoke_with_call_chain at /opt/jruby/lib/ruby/gems/shared/gems/rake-13.0.1/lib/rake/task.rb:199
                  invoke at /opt/jruby/lib/ruby/gems/shared/gems/rake-13.0.1/lib/rake/task.rb:188
                  launch at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/launcher.rb:140
      launch_application at /opt/jruby/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.17.2.2/lib/glimmer/launcher.rb:188

**Comment by AndyObtiva** [comment]
OK, you still have a problem with your Git setup:

Please specify --github-username or set github.user in ~/.gitconfig (see http://github.com/blog/180-local-github-config for details). For example: git config --global github.user defunkt

Please fix it by running:

```
git config --global github.user mistergibson
```

Pay attention to error messages. They are helpful and often provide you with hints that are the exact solution you are looking for.

**Comment by mistergibson** [comment]
OK - got it working, but it was weird:

I had to be in a .git directory (from my gitlab repo) to run glimmer scaffold, who creates the project dir and *another* .git inhabited dir in that. Also, I am using my own gitlab repo -- not github as your script appears to assume. It does run, which is friggin cool, but when I attempt to re-run it with "glimmer run" it cannot find jruby even though env jruby points home correctly.

Hope that helps.

So, love that I got it running, but don't understand the .git on .git assumptions you're making.

**Comment by AndyObtiva** [comment]
There is no such thing as a "glimmer run" command. But, assuming you mean "glimmer application", you would just have to replace "application" with the the path to the application binary script, which gets scaffolded automatically under the "bin" directory.

For example, if you scaffolded 'some_app', then `cd` into it and run this:

```
glimmer bin/some_app
```

**Comment by mistergibson** [comment]
oh right ok --> thanks

**Comment by AndyObtiva** [comment]
You're welcome.
